apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: rabbitmq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbit3
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      name: cpu
        target: 
          type: Utilization
          averageUtilization: 60
      name: memory
        target: 
          type: AverageValue
          averageValue: 120Mi
status:
  observedGeneration: 1
  lastScaleTime: 
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageUtilization: 0
          averageValue: 0
      resource: 
        name: memory
          current: 
            averageValue: 0