apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workerroll
spec:
  selector:
    matchLabels:
      app: workerroll
  replicas: 1
  template:
    metadata:
      labels:
        app: workerroll
    spec:
      containers:
      - name: workerroll
        image: pconnell89/rollworker
        resources:
          requests:
            cpu: 100m 
            memory: 100Mi 
        env:
        - name: RMQ_HOST
          value: rabbitmq
        - name: RMQ_PORT
          value: "5672"
        - name: GET_HOSTS_FROM
          value: dns
---          
# apiVersion: v1
# kind: Service
# metadata:
#   name: workerchar
#   labels:
#     app: workerchar
#     tier: backend
# spec:
#   ports:
#   selector:
#     app: workerchar
#     tier: backend