apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workerinit
spec:
  selector:
    matchLabels:
      app: workerinit
  replicas: 1
  template:
    metadata:
      labels:
        app: workerinit
    spec:
      containers:
      - name: workerinit
        image: pconnell89/initworker
        resources:
          requests:
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m
            memory: 100Mi
        env:
        - name: RMQ_HOST
          value: production-rabbitmqcluster # rabbitmq
        - name: RMQ_PORT
          value: "5672"
        - name: GET_HOSTS_FROM
          value: dns
---
#autoscale config  
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workerinit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workerinit
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
      name: memory
      target:
        type: AverageValue
        averageValue: 75Mi