apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workerdb
spec:
  selector:
    matchLabels:
      app: workerdb
  replicas: 1
  template:
    metadata:
      labels:
        app: workerdb
    spec:
      containers:
      - name: workerdb
        image: pconnell89/dbworker #workerdb
        resources:
          requests:
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m
            memory: 100Mi
        env:
        - name: RMQ_HOST
          value: production-rabbitmqcluster #rabbitmq
        - name: RMQ_PORT
          value: "5672"
        - name: CASS_HOST
          value: "cassdb01-cassandra"
        - name: CASS_PORT
          value: "9402"
        - name: CASS_USER
          value: cassandra
        - name: CASS_PASS
          value: changeme
        - name: GET_HOSTS_FROM
          value: dns
---
#autoscale config  
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workerdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workerdb
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 75Mi
# status:
#   observedGeneration: 1
#   currentReplicas: 1
#   desiredReplicas: 10
#   currentMetrics:
#   - type: Resource
#     resource:
#       name: cpu
#     current:
#       averageUtilization: 0
#       averageValue: 0
  