apiVersion: v1
kind: Service
metadata:
  name: cassdb
  labels:
    app: cassdb
    tier: frontend
spec:
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassdb
    tier: frontend
---
