# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workerChar.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'workerChar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10workerChar.proto\"@\n\nsetcharmsg\x12\x10\n\x08main_cmd\x18\x01 \x01(\t\x12\x11\n\tchild_cmd\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\" \n\x0csetcharreply\x12\x10\n\x08response\x18\x01 \x01(\t\"-\n\ngetcharmsg\x12\x10\n\x08main_cmd\x18\x01 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\" \n\x0cgetcharreply\x12\x10\n\x08response\x18\x01 \x01(\t22\n\x07setChar\x12\'\n\x07setChar\x12\x0b.setcharmsg\x1a\r.setcharreply\"\x00\x32\x32\n\x07getChar\x12\'\n\x07getChar\x12\x0b.setcharmsg\x1a\r.getcharreply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workerChar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETCHARMSG']._serialized_start=20
  _globals['_SETCHARMSG']._serialized_end=84
  _globals['_SETCHARREPLY']._serialized_start=86
  _globals['_SETCHARREPLY']._serialized_end=118
  _globals['_GETCHARMSG']._serialized_start=120
  _globals['_GETCHARMSG']._serialized_end=165
  _globals['_GETCHARREPLY']._serialized_start=167
  _globals['_GETCHARREPLY']._serialized_end=199
  _globals['_SETCHAR']._serialized_start=201
  _globals['_SETCHAR']._serialized_end=251
  _globals['_GETCHAR']._serialized_start=253
  _globals['_GETCHAR']._serialized_end=303
# @@protoc_insertion_point(module_scope)
