apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest
    tier: frontend
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - image: pconnell89/testrest   # Edit this for your reponame
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: RMQ_HOST
          value: rabbitmq
        - name: RMQ_PORT
          value: "5672"
        - name: GET_HOSTS_FROM
          value: dns
        name: master
        ports:
        - containerPort: 5000