# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workerRoll.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'workerRoll.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10workerRoll.proto\"\\\n\trollReply\x12\x0c\n\x04\x64ice\x18\x01 \x03(\x05\x12\x10\n\x08mod_dice\x18\x02 \x03(\x05\x12\x10\n\x08roll_sum\x18\x03 \x01(\x05\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\"I\n\rrollAttackmsg\x12\x0b\n\x03\x61\x64v\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61\x64v\x18\x02 \x01(\x08\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"K\n\x0frollIniativemsg\x12\x0b\n\x03\x61\x64v\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61\x64v\x18\x02 \x01(\x08\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"L\n\x10rollSpellcastmsg\x12\x0b\n\x03\x61\x64v\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61\x64v\x18\x02 \x01(\x08\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"I\n\rrollDamagemsg\x12\x0b\n\x03\x61\x64v\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61\x64v\x18\x02 \x01(\x08\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"G\n\x0brollSavemsg\x12\x0b\n\x03\x61\x64v\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61\x64v\x18\x02 \x01(\x08\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t28\n\nrollAttack\x12*\n\nrollAttack\x12\x0e.rollAttackmsg\x1a\n.rollReply\"\x00\x32\x42\n\x0erollInitiative\x12\x30\n\x0erollInitiative\x12\x10.rollIniativemsg\x1a\n.rollReply\"\x00\x32\x41\n\rrollSpellcast\x12\x30\n\rrollSpellcast\x12\x11.rollSpellcastmsg\x1a\n.rollReply\"\x00\x32\x38\n\nrollDamage\x12*\n\nrollDamage\x12\x0e.rollDamagemsg\x1a\n.rollReply\"\x00\x32\x32\n\x08rollSave\x12&\n\x08rollSave\x12\x0c.rollSavemsg\x1a\n.rollReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workerRoll_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLLREPLY']._serialized_start=20
  _globals['_ROLLREPLY']._serialized_end=112
  _globals['_ROLLATTACKMSG']._serialized_start=114
  _globals['_ROLLATTACKMSG']._serialized_end=187
  _globals['_ROLLINIATIVEMSG']._serialized_start=189
  _globals['_ROLLINIATIVEMSG']._serialized_end=264
  _globals['_ROLLSPELLCASTMSG']._serialized_start=266
  _globals['_ROLLSPELLCASTMSG']._serialized_end=342
  _globals['_ROLLDAMAGEMSG']._serialized_start=344
  _globals['_ROLLDAMAGEMSG']._serialized_end=417
  _globals['_ROLLSAVEMSG']._serialized_start=419
  _globals['_ROLLSAVEMSG']._serialized_end=490
  _globals['_ROLLATTACK']._serialized_start=492
  _globals['_ROLLATTACK']._serialized_end=548
  _globals['_ROLLINITIATIVE']._serialized_start=550
  _globals['_ROLLINITIATIVE']._serialized_end=616
  _globals['_ROLLSPELLCAST']._serialized_start=618
  _globals['_ROLLSPELLCAST']._serialized_end=683
  _globals['_ROLLDAMAGE']._serialized_start=685
  _globals['_ROLLDAMAGE']._serialized_end=741
  _globals['_ROLLSAVE']._serialized_start=743
  _globals['_ROLLSAVE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
