# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import workerChar_pb2 as workerChar__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in workerChar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class setCharStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setChar = channel.unary_unary(
                '/setChar/setChar',
                request_serializer=workerChar__pb2.setcharmsg.SerializeToString,
                response_deserializer=workerChar__pb2.setcharreply.FromString,
                _registered_method=True)


class setCharServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setChar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_setCharServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setChar': grpc.unary_unary_rpc_method_handler(
                    servicer.setChar,
                    request_deserializer=workerChar__pb2.setcharmsg.FromString,
                    response_serializer=workerChar__pb2.setcharreply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'setChar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('setChar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class setChar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setChar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setChar/setChar',
            workerChar__pb2.setcharmsg.SerializeToString,
            workerChar__pb2.setcharreply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class getCharStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getChar = channel.unary_unary(
                '/getChar/getChar',
                request_serializer=workerChar__pb2.setcharmsg.SerializeToString,
                response_deserializer=workerChar__pb2.getcharreply.FromString,
                _registered_method=True)


class getCharServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getChar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getCharServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getChar': grpc.unary_unary_rpc_method_handler(
                    servicer.getChar,
                    request_deserializer=workerChar__pb2.setcharmsg.FromString,
                    response_serializer=workerChar__pb2.getcharreply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getChar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('getChar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class getChar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getChar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/getChar/getChar',
            workerChar__pb2.setcharmsg.SerializeToString,
            workerChar__pb2.getcharreply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
